package db

import (
	"context"
	"fmt"
	"sync"
	"time"
)

// Driver is the interface that must be implemented by a database driver.
//
// Drivers register themselves via Register and are selected by engine name
// when calling Open, following the same pattern as database/sql.
type Driver interface {
	// Open returns a new connection to the database.
	Open(cfg Config) (Conn, error)
}

// Conn is the minimal interface that every database connection must implement.
// This is the common ground that works across SQL, document, and key-value stores.
type Conn interface {
	// Get retrieves a single record by its primary key.
	// dest must be a pointer to a struct or map.
	Get(ctx context.Context, collection string, id any, dest any) error

	// Set creates or replaces a record.
	// data must be a struct or map.
	Set(ctx context.Context, collection string, id any, data any) error

	// Delete removes a record by its primary key.
	Delete(ctx context.Context, collection string, id any) (int64, error)

	// Close closes the connection and releases resources.
	Close() error
}

// Querier is an optional interface for engines that support filtered queries.
// SQL databases and document stores (MongoDB, etc.) typically implement this.
type Querier interface {
	// Exec executes a query that doesn't return rows (INSERT, UPDATE, DELETE).
	Exec(ctx context.Context, query string, args ...any) (Result, error)

	// Query executes a query that returns rows.
	Query(ctx context.Context, query string, args ...any) (Rows, error)

	// QueryRow executes a query that returns at most one row.
	QueryRow(ctx context.Context, query string, args ...any) Row
}

// Transactioner is an optional interface for engines that support ACID transactions.
type Transactioner interface {
	// Begin starts a new transaction.
	Begin(ctx context.Context) (Tx, error)
}

// Tx represents a database transaction.
type Tx interface {
	Conn
	Querier

	// Commit commits the transaction.
	Commit() error

	// Rollback aborts the transaction.
	Rollback() error
}

// Expirer is an optional interface for engines that support TTL on records (Redis, DynamoDB).
type Expirer interface {
	// SetWithTTL creates or replaces a record with an expiration time.
	SetWithTTL(ctx context.Context, collection string, id any, data any, ttl time.Duration) error
}

// Row represents a single row returned by QueryRow.
type Row interface {
	// Scan copies the row's columns into dest.
	Scan(dest ...any) error
}

// Rows represents a result set returned by Query.
type Rows interface {
	// Next advances to the next row. Returns false when no more rows.
	Next() bool

	// Scan copies the current row's columns into dest.
	Scan(dest ...any) error

	// Close releases the resources held by this result set.
	Close() error

	// Err returns any error that occurred during iteration.
	Err() error
}

// Result represents the result of an Exec operation.
type Result struct {
	// RowsAffected is the number of rows affected by the operation.
	RowsAffected int64

	// LastInsertID is the ID generated by the database for an INSERT.
	// Not all engines support this.
	LastInsertID int64
}

var (
	driversMu sync.RWMutex
	drivers   = make(map[Engine]Driver)
)

// Register makes a database driver available by the provided engine name.
// It panics if a driver is already registered for the same engine.
//
// This is typically called from a driver package's init function:
//
//	func init() {
//	    db.Register(db.EnginePostgreSQL, &PostgresDriver{})
//	}
func Register(engine Engine, driver Driver) {
	driversMu.Lock()
	defer driversMu.Unlock()

	if _, exists := drivers[engine]; exists {
		panic(fmt.Sprintf("db: driver already registered for engine %q", engine))
	}
	drivers[engine] = driver
}

// Drivers returns a list of registered engine names.
func Drivers() []Engine {
	driversMu.RLock()
	defer driversMu.RUnlock()

	list := make([]Engine, 0, len(drivers))
	for engine := range drivers {
		list = append(list, engine)
	}
	return list
}

func getDriver(engine Engine) (Driver, error) {
	driversMu.RLock()
	defer driversMu.RUnlock()

	d, ok := drivers[engine]
	if !ok {
		return nil, fmt.Errorf("%w: %s", ErrNoDriver, engine)
	}
	return d, nil
}
