package builder

import "context"

// Executor is the interface used by builders to execute queries against a database.
// This is implemented by *db.DB to break the import cycle between db and builder packages.
type Executor interface {
	ExecBuilder(ctx context.Context, query string, args ...any) (Result, error)
	ScanBuilder(ctx context.Context, dest any, query string, args ...any) error
}

// Result represents the result of an exec operation (INSERT, UPDATE, DELETE).
type Result struct {
	// RowsAffected is the number of rows affected by the operation.
	RowsAffected int64

	// LastInsertID is the ID generated by the database for an INSERT.
	// Not all engines support this.
	LastInsertID int64
}
